# Generated by Django 2.1.3 on 2018-11-30 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=255, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=14, verbose_name='Номер')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Department', verbose_name='Департамент')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='ruler',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='this_ruller', to='company.Employee', verbose_name='Руководитель'),
        ),
        migrations.AddField(
            model_name='company',
            name='ruler',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.Employee', verbose_name='Руководитель'),
        ),
    ]
