# Generated by Django 2.1.3 on 2018-11-30 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='company',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='company.Company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='company',
            name='ruler',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.Employee', verbose_name='Руководитель'),
        ),
        migrations.AlterField(
            model_name='department',
            name='ruler',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='this_ruller', to='company.Employee', verbose_name='Руководитель'),
        ),
    ]
